# Final Project Proposal

Please complete your proposal following the outline below.

## Project title

Analysis of FF vs MM households in Gayborhood areas

### Authors
Kelvin Teng, Josh Lee , October Allen
### Date
05/17/2024

### Abstract

Our project aims to explore the relationship between Female same sex couples and Male same sex couples in gayborhood areas. We hope to analyze marraige patterns in certain zip codes and overall, as well as comparison between the % married for Femal versus male and in general wether there are more Female or Male couples in these areas. 


### Keywords

gay, pride, gayborhood, lesbian, marraige, statistics

### Proposal

Our project delves into the differences in same-sex couples for males and females. Our hope is that this research could be contributed to social science relating to gender differences, societal structures specifically relating to LGBTQ populations.  The questions we pose include:  

1. How do the rates for same sex couples marraige compare between genders?

2. What influences the concentration of same-sex relationships in some regions compared to others?

3. Are there significant differences between marraige practices in certain areas or is there a larger trend between genders or no correlation for either?

Understanding these questions is crucial in analyzing the way our social structure works, gender norms, LGBTQ life and influences and if there are differences this could lead to more research about the possible cause of such differences and if there are underlying issues. Understanding pieces of a complex society helps in building adequete structures and understanding / documenting the history happening around the world every day. Knowing about social trends can tell so much about the development and health of a culture and can lead to better social programs for aiding affected parties, but also can just be useful to document and compare over time.


### Related Work / references: 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7978662/

https://www.researchgate.net/publication/250171430_Neighborhood_Factors_Associated_with_Same-Sex_Households_in_US_Cities

https://www.theguardian.com/cities/2016/jan/13/end-of-gaytrification-cities-lgbt-communities-gentrification-gay-villages

### The Dataset:
Found on The Pudding: 
The-pudding/data/gayborhoods/README.md
The dataset we chose features information about Gay and Lesbian households, their marraige status, zip codes, straight couples in the area, gay bars in the area, ratios of amounts of gay, lesbian, and same-sex couples in general compared to all households and more. 

### Implications:
This data can be used to analyze social patterns in certain areas where marraige may be higher in general, among straight couples, same-sex couples or even specifically gay or lesbian couples. This can also be compared with LGBTQ affiliated businesses in the area to see if that affects any patterns to map social tendancies in gayborhoods.

### Limitations & Challenges:
Although patterns may be able to be formed from this data, the dataset isnt incredibly large so analysis may not be applicable to the greater area. There are also so many factors besides location complicating social patterns such as marraige and clustering of couples of a certain identity that it's difficult to tie a trend to a certain area. There could also be inconsistancies in the data due to lack of registration of married couples and especially non married couples.

 ### Acknowledgements:
We would like to thank our Teaching Assistant, Mie, our Professor, and The-Pudding for making this project possible. 

# Table

```dataTable <- dataset %>%
     group_by(GEOID10) %>%
     arrange(desc(Cns_RateSS)) %>%
     ungroup() %>%
     filter(row_number() <= 10) %>%
     select(GEOID10, CountBars, ParadeFlag) %>%
     rename(`Zipcode` = GEOID10,
            `Gay Bars` = CountBars,
            `Pride March Boolean` = ParadeFlag)
```
The reason we included this table was to show the relationship between having gay bars and pride marchs in a zipcode. Instinctively, we might assume that zipcodes with a lot of gay bars would also be an area with pride marchs. In addition, we may also assume that zipcodes with a high rate of same sex couples would have a lot of gay bars and have a pride march. While these are generally true, the table highlights important exceptions that recontextualize how we view these zipcodes. Zipcodes 94114 and 94131, for example, are in New York City and San Francisco respectively, but both zipcodes have no pride marches in the area. This would be because there are just one zipcode in cities with a large queer representation, so other zipcodes in the city would have such pride marches to compenseate. 

# Chart 1

For chart 1, we made a bar graph comparing the rate of married same-sex couples between the 5 most populous zipcodes in the dataset. The purpose is to compare these zipcodes and see if there is anything about a large population that adds to the rate of same sex couples. We can see in the chart that there is a lot of variation between the rates of same sex couples in these areas, even though they are all around the same population. This shows that just because the zipcode is in a big, metropolitan progressive hub, it doesn't necessarily translate to more same sex couples. Factors such as accessibility to queer resources are presumably a bigger contributor to the rate of same sex couples. 

# Chart 2

For chart 2, we made a scatter plot showing the correlation between the number of gay bars and unmarried same sex couples. We included this because, as posed in the explanation for Chart 1, we wanted to see the direct correlation between a factor that may increase the rate of same sex couples in an area unrelated to population. As we can see in the chart, there is a positive trend that indicates that more gay bars, a place where people may find love and be registered as a couple, increases the rate of same sex couples. Some inconsistencies in the data could be attributed to the fact that areas with no gay bars, such as certain zipcodes in metropolitans like New York, may still have a large gay population that simply travels to nearby areas that do have gay bars. This would result in data points with a low number of gay bars and a high number of same sex couples. 

# Chart 3

For chart 3, we made another bar graph highlighting the zipcodes with the highest rate of married same sex couples. We included this chart because it shows which cities have the highest rate of couples while also comparing these areas against eachother, which highlight differences that might attribute to the varying numbers. The zipcode with the highest rate of same sex couples, 94114, is located in San Francisco. This is not surprising, as San Francisco has a rich history of having a vibrant queer community. Interestingly, each zipcode is located in a drastically different location from one another, ranging from Boston, MA to LA to New York. This bar chart highlights that big, metropolitan hubs with a history of queer representation and resources tend to have higher rates of same sex couples. 



