## Question
What is the relationship between zip codes and the rate of same-sex married couples in the most populated zip codes?


## Summary
The bar chart displays the rate of same-sex married couples across the five most populated zip codes. The zip codes included in the analysis are 10025, 11211, 11226, 60618, and 60657. 
The rate of same-sex married couples varies significantly among these regions:
10025: This zip code has the highest rate of same-sex married couples, with a rate exceeding 30.
11211: This zip code shows a lower rate of approximately 12 same-sex married couples.
11226: This area has a moderate rate of around 18 same-sex married couples.
60618: The rate here is relatively low, at approximately 10 same-sex married couples.
60657: This zip code has a higher rate of same-sex married couples, with a rate close to 30, similar to 10025.


'''{R}
library(ggplot2)
library(dplyr)
library(readr)
dataset <- read_csv("Downloads/data.csv")
top5 <- dataset %>%
    top_n(5, Cns_TotHH) %>%
    arrange(TaxRate_SS)
zipCode <- top5 %>%
    pull(GEOID10)
chart1 <- ggplot(top5)+
  geom_col(mapping = aes(x = zipCode, y = TaxRate_SS))+
  labs(
    title = "Most Populated Zipcodes versus Rate of Same-Sex Married Couples",
    x = "Most Populated Zipcodes",
    y = "Rate of Same-Sex Married Couples"
    )
'''


The chart suggests that there is a notable variation in the rate of same-sex married couples across different zip codes, indicating that certain areas may be more favorable or supportive environments for same-sex couples. 
Understanding the factors that contribute to these differences can provide insights into community acceptance, housing policies, and social dynamics that influence where same-sex couples choose to reside.







